version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - cd reactapp
      - npm i
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'reactApp/build' # adjust if your build output is stored in a different directory
